### ISSUE TITLE
Goals of webcompat-to-bugzilla

### ISSUE THREAD

**Issue by karlcow** [MDTsai/webcompat-to-bugzilla#1]
* [ ]  clone an issue from webcompat.com to bugzilla
  - create a new issue with description (steps to reproduce), URL, title and linking back to the webcompat.com (I usually say this is a spin off of issue [number] on webcompat.com)
  - https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Layout (how do we fetch the right product/component?)
  - Plus add a comment on the github issue that the mozilla bug has been opened.
* [ ] Add an issue as a duplicate of one on bugzilla
  - Propose a box with a list of common duplicates (hls, zoom, input padding, etc) and/or a form for the bug number.
  - Close the webcompat.com issue
  - Adds a comment in the webcompat.com issue with the number of the duplicate.
  - Adds a seeAlso on the bugzilla bug.

**Comment by karlcow** [comment]
These are not necessary complete and maybe we don't need (or not possible) to implement everything.

**Comment by MDTsai** [comment]
@adamopenweb do you need to add comment/requirement on this?

**Comment by adamopenweb** [comment]
Looks great to me!

**Comment by MDTsai** [comment]
Thanks for the input. This is what in prototype now. Everything works but not complete. I will file new issues for new features.
![2017-08-17 17-23-27](https://user-images.githubusercontent.com/5763237/29405749-682783a0-8371-11e7-8617-dca21a2d26d2.png)

**Comment by MDTsai** [comment]
so far version 1.1 could do all of these. close this issue for now.
