### ISSUE TITLE
Unix error 2 (wat...?) in console

### ISSUE THREAD

**Issue by miketaylr** [MDTsai/webcompat-to-bugzilla#16]
When trying to open the debugger to see what #15 is about, I get the following error in the console (twice):

```
Unix error 2 during operation DirectoryIterator.prototype.next on file /Users/miket/Downloads/webcompat-to-bugzilla-master/_locales (No such file or directory)  Extension.jsm:387
	readDirectory resource://gre/modules/Extension.jsm:387:9
	throw self-hosted:1205:9
```

![screen shot 2017-08-31 at 12 00 43 pm](https://user-images.githubusercontent.com/67283/29935346-0f06b196-8e44-11e7-926e-10395e5276cc.png)

**Comment by MDTsai** [comment]
I'm not able to reproduce this issue. There is no _locales directory for me.

**Comment by miketaylr** [comment]
Let's go ahead and close it.
