### ISSUE TITLE
Disable all browser action buttons on install

### ISSUE THREAD

**Issue by miketaylr** [MDTsai/webcompat-to-bugzilla#18]
Currently the addon will enable/disable a browser action button when a page is loaded:

https://github.com/MDTsai/webcompat-to-bugzilla/blob/master/background.js#L59

When the addon is first loaded, all existing tabs will have an enabled button. (This is obviously not the most important issue....)

**Comment by MDTsai** [comment]
Let's preload a list to prevent this. Not disable button.
