### ISSUE TITLE
When on github.com gives the possibility to redirect to webcompat.com

### ISSUE THREAD

**Issue by karlcow** [MDTsai/webcompat-to-bugzilla#27]
@MDTsai thanks for the addon.

When the domain is https://github.com/webcompat/web-bugs/issues/ create a possibility to redirect to the same issue on webcompat.com or even better inject in the DOM (if possible) a link to the right issue on webcompat.com

**Comment by magsout** [comment]
Cool features

**Comment by MDTsai** [comment]
Current proposal, append to issue title with "Go to WebCompat.com". Click will go back to original issue in webcompat.com. Looks normal but works, any suggestion?
![2017-11-01 17-33-26](https://user-images.githubusercontent.com/5763237/32268645-ee02832c-bf2a-11e7-8d96-a5d28de75682.png)

**Comment by miketaylr** [comment]
That's cool, thanks @MDTsai.

**Comment by karlcow** [comment]
Thanks a million times. This will save us a lot of times.
