### ISSUE TITLE
Separate list for common issues

### ISSUE THREAD

**Issue by karlcow** [MDTsai/webcompat-to-bugzilla#28]
It would be cool for a new version of the extension to have a separate file for 

https://github.com/MDTsai/webcompat-to-bugzilla/blob/5e008106968c3da6f4a85c0aa9b9d4be8b92f69c/background.js#L100-L115

So we can update it on GitHub through pull request. 
And maybe having the extension fetching the updates once a week on github directly? (if possible)

**Comment by MDTsai** [comment]
It's preloaded, but the extension will load new list from https://github.com/MDTsai/webcompat-to-bugzilla/blob/5e008106968c3da6f4a85c0aa9b9d4be8b92f69c/background.js#L9 after extension reloaded.
Not sure if it's what @karlcow  want?

**Comment by karlcow** [comment]
Ah! very cool! It seems this is what I want.

1. If I do a pull request on background.js with more data, the extension will benefit of it.
2. How do we reload an extension?
3. What about a preference panel for the extension saying reload the list of issues?

**Comment by MDTsai** [comment]
> 1. If I do a pull request on background.js with more data, the extension will benefit of it.

I will also sync with my repo, or we can have another file which is public? like in webcompat.com repo?

> 2. How do we reload an extension?

In about:addon, disable/enable? Restart firefox also works
> 3. What about a preference panel for the extension saying reload the list of issues?

It's possible, maybe reload every hour? which is more simple.

**Comment by karlcow** [comment]
Thanks. 

1. if sync your repo, adjust the list on the extension +1
2. ok
3. Reload sounds simpler indeed.

**Comment by MDTsai** [comment]
1. will adjust the list on the extension, but may not publish to AMO at the same time if only update the list.
3. Now design to reload every hour, should works for normal use case I guess.
