### ISSUE TITLE
Extension Design - a bit of stardust style

### ISSUE THREAD

**Issue by karlcow** [MDTsai/webcompat-to-bugzilla#29]
@MDTsai Are you interested?

<img width="416" alt="capture d ecran 2017-10-24 a 16 12 34" src="https://user-images.githubusercontent.com/505230/31929262-520844fc-b8d6-11e7-8adc-fea36daf4381.png">

I can send a pull request if you want.

**Comment by MDTsai** [comment]
Thanks @karlcow let's do this!
