### ISSUE TITLE
Closing as a duplicate of a preselected bug failed.

### ISSUE THREAD

**Issue by karlcow** [MDTsai/webcompat-to-bugzilla#31]
@MDTsai While closing an issue as duplicate with a predefined bug, it failed.

![capture d ecran 2017-10-26 a 16 11 26](https://user-images.githubusercontent.com/505230/32039289-73a5153e-ba68-11e7-9c6e-7e635b812114.png)

**Comment by MDTsai** [comment]
I just close https://github.com/webcompat/web-bugs/issues/13013 using version 1.1 without any problem. From the internal error of bugzilla I don't think it's about the extension. You can try to use v1.1 and see if this is still a problem.

**Comment by karlcow** [comment]
Working. No issue. Thanks @MDTsai
