### ISSUE TITLE
Webcompat issue link is not always added to “See also” field in Bugzilla

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [MDTsai/webcompat-to-bugzilla#35]
URL: https://webcompat.com/ 
Browser / Version: Firefox Nightly 63.0a1 (2018-08-21)
Operating System: Windows 10 Pro

**Prerequisites:**
    1. “WebCompat to Bugzilla” extension installed.

**Steps to Reproduce:**
    1. Navigate to https://webcompat.com/ 
    2. Tap “All issues” and click an issue from the list. 
    3. Click the “WebCompat to Bugzilla” button.
    4. Select the “Files a new bug” and choose the correct “Product” and “Component” from the drop-down menu.
    5. After being redirected to Bugzilla, scroll down to “See also” field. 
       
**Expected Behavior:**
The field is populated with the Webcompat issue link.

**Actual Behavior:**
The field is not populated with the Webcompat issue link.

**Note**
    1. Reproducible: random (2/5)
    2. Screenshot attached.

![image](https://user-images.githubusercontent.com/12184325/44471748-3952b800-a635-11e8-852d-50e1ffc2c754.png)
       
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

**Comment by MDTsai** [comment]
Bugzilla UI seems changed on my computer, I can't go to the create bug page directly but redirected to a "find similar bug" page instead. It's why the function doesn't work for me. @softvision-oana-arbuzov is that the same on your side?

**Comment by softvision-oana-arbuzov** [comment]
I don't get any error, I'm redirected to a new bug page in Bugzilla with some fields populated.

![screenshot_3](https://user-images.githubusercontent.com/12184325/44508832-62685c80-a6b8-11e8-80e7-a37345362e8b.png)

**Comment by softvision-oana-arbuzov** [comment]
I don't get any error, I'm redirected to a new bug page in Bugzilla with some fields populated.

![screenshot_3](https://user-images.githubusercontent.com/12184325/44509441-5e3d3e80-a6ba-11e8-8372-2761feef31d3.png)

**Comment by MDTsai** [comment]
@softvision-oana-arbuzov I fix the issue but I may need your help to test this.

1. Remove original extension
2. Download source code from https://github.com/MDTsai/webcompat-to-bugzilla/, you can use zip then extract to somewhere
3. Go to about:debugging
4. Click "Temp load extension", choose the manifest.json in the folder you download in step 2
5. You have the code works until Firefox restart.

If this fix works, I will push to AMO for everyone. Thanks!

**Comment by softvision-oana-arbuzov** [comment]
@MDTsai I've made some tests with different Webcompat issues and different Products and Components, and it seems to be working fine, every time the link was added to the "See also" field.

**Tested with:**
Browser / Version: Firefox Nightly 64.0a1 (2018-09-24)
Operating System: Windows 10 Pro

Feel free to push it to AMO. Thanks.

**Comment by MDTsai** [comment]
Pushed, wait for approval.

**Comment by softvision-oana-arbuzov** [comment]
@MDTsai there is a different problem that occurred and it is still reproducible with the temporary extension.
"URL" field is populated with browser version instead of the URL link.

![image](https://user-images.githubusercontent.com/12184325/46077389-6268ea00-c199-11e8-89fa-f9c1bec6d778.png)

Could you have a look?

**Comment by MDTsai** [comment]
Yes, I will take look today and give a quick patch. Not sure if it's because the format change?

**Comment by MDTsai** [comment]
@softvision-oana-arbuzov I found I fix this issue according to web-bugs/issues/19108 but it's not a normal case. I rollback to original bug report form. Could you try the new patch as https://github.com/MDTsai/webcompat-to-bugzilla/issues/35#issuecomment-424268246 ?

**Comment by softvision-oana-arbuzov** [comment]
@MDTsai, I've retested the issue while being logged in ant the "See also" and "URL" fields are correctly populated.

**Note:**
If I'm not logged when using the Extension, "See also" and "URL" and many other fields are not displayed.
![image](https://user-images.githubusercontent.com/12184325/46149898-feffba80-c273-11e8-931d-2d6883500af0.png)
