### ISSUE TITLE
Remove list of known bugs

### ISSUE THREAD

**Issue by karlcow** [MDTsai/webcompat-to-bugzilla#36]
@MDTsai After daily usage of this wonderful addon in the context of our work, I realized that I almost never use the second option. "Add to common bugs".

So two options here.

1. Remove it
2. Remove it and Replace it by a list of recent bugs. 

The way option 2 would be working.
1. Each time we add a bug to the seeAlso
2. Collect the bugzilla number and its title and increment a hit counter for this specific number.
3. Then each time, we choose "Add to bug's see also" and focus the cursor into the input, display a list of the most recent bugs ordered by the frequency we duplicate against.

Make sure to update the title when the title change on bugzilla. That could be done for example, when using the same number again, double check the title has not changed.

**Comment by MDTsai** [comment]
Yes, the list is too old. Let users maintain their own list sounds a good idea. Consider heavy user like webcompat team, we can only show the top 10 bugs in the list but still have all the bugs in db.
BTW, original idea is to have a list from all users to share.

**Comment by MDTsai** [comment]
@karlcow  I will do option 2, replace with list of 10 or 15 frequently used bugs. Update bug title is done when add to bug's see also. Will done by 2019.

**Comment by karlcow** [comment]
❤️ Thanks a lot @MDTsai

**Comment by MDTsai** [comment]
Close as done.
