### ISSUE TITLE
Remove default P3 setting for new bugs

### ISSUE THREAD

**Issue by miketaylr** [MDTsai/webcompat-to-bugzilla#37]
Most teams use triage dashboards that only consider bugs without priorities. The following likely has prevented some bugs from being noticed:

https://github.com/MDTsai/webcompat-to-bugzilla/blob/c9fe2a7184f1e5711222a7fd8d9c8abfd41a62a6/content_scripts/new_bug.js#L76

@MDTsai could we get an updated version published removing that? I can send a PR if it helps.

**Comment by MDTsai** [comment]
Sure, so remove P3 let it become no priority? PR is welcome!
